# Promtail config
server:
  disable: true

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://mgmt:3100/loki/api/v1/push

scrape_configs:
- job_name: authlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: authlog
      shipper: promtail
      __path__: /var/log/auth.log

- job_name: daemonlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: daemonlog
      shipper: promtail
      __path__: /var/log/daemon.log

- job_name: syslog
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslog
      shipper: promtail
      __path__: /var/log/syslog

- job_name: dpkglog
  static_configs:
  - targets:
      - localhost
    labels:
      job: dpkg
      shipper: promtail
      __path__: /var/log/dpkg.log

- job_name: cronlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: cronlog
      shipper: promtail
      __path__: /var/log/cron.log
