# Main k8s Setup

# https://k9scli.io/
- name: Get latest k9s release
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases/latest
    return_content: yes
    status_code: [200]
  register: k8s_intanal_k9s_release_res
  tags: [k8s, k8s-hetzner, k8s-k9s]

- name: Install k9s
  unarchive:
    src: '{{ k8s_intanal_k9s_release_res.json | community.general.json_query(myquery) | first }}'
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  vars:
    myquery: "assets[?contains(name,'Linux_amd64')].browser_download_url"
  tags: [k8s, k8s-hetzner, k8s-k9s]
