# Main k8s CNI - Calico

- name: Add projectcalico helm chart repo
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://projectcalico.docs.tigera.io/charts
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8s-calico]

- name: Install Calico
  kubernetes.core.helm:
    name: calico
    state: present
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    update_repo_cache: true
    create_namespace: true
    wait: true
    values: '{{ k8s_calico_helm_values | default({}) }}'
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8s-calico]

- name: Download calicoctl
  get_url:
    url: https://github.com/projectcalico/calico/releases/download/v3.24.1/calicoctl-linux-amd64
    dest: /usr/bin/kubectl-calico
    mode: '0754'
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8s-calico]

